apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: "managed"
    app: {{ .Values.name }}
  annotations:
    prometheus.io/port: '{{ .Values.metricsPort }}'
    prometheus.io/scrape: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        giantswarm.io/service-type: "managed"
        app: {{ .Values.name }}
      annotations:
        {{- if and (eq .Values.provider "aws") (eq .Values.route53.access "internal") }}
        iam.amazonaws.com/role: {{ .Values.clusterID}}-Route53Manager-Role
        {{- end }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
        fsGroup: {{ .Values.groupID }}
      priorityClassName: giantswarm-critical
      {{- if and (eq .Values.provider "aws") (eq .Values.route53.access "internal") }}
      initContainers:
      - name: wait-for-iam-role
        image: {{ .Values.image.registry }}/giantswarm/alpine:3.10
        command:
        - /bin/sh
        - -c
        - counter=5; while ! wget -qO- http://169.254.169.254/latest/meta-data/iam/security-credentials/ | grep {{ .Values.clusterID}}-Route53Manager-Role; do echo 'Waiting for iam-role to be available...'; sleep 5; let "counter-=1"  ; if [ "$counter" -eq "0" ]; then exit 1; fi; done
      {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        {{- if eq .Values.route53.access "external" }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.route53.secret.name }}
              namespace: {{ .Values.route53.secret.namespace }}
              key: {{ .Values.route53.key }}.aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.route53.secret.name }}
              namespace: {{ .Values.route53.secret.namespace }}
              key: {{ .Values.route53.key }}.aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.route53.region }}
        {{- end }}
        args:
        {{- range .Values.sources }}
        - --source={{ . }}
        {{- end }}
        - --provider={{ .Values.provider }}
        {{- if eq .Values.provider "azure" }}
        - --azure-config-file=/azure/config/azure.yaml
        {{- end }}
        {{- if eq .Values.route53.access "external" }}
        - --domain-filter={{ .Values.route53.baseDomain }}
        - --aws-zone-type=public
        {{- else }}
        - --domain-filter={{ .Values.baseDomain }}
        {{- end }}
        - --metrics-address=:{{ .Values.metricsPort }}
        - --namespace={{ .Values.namespace }}
        - --registry=txt
        - --txt-owner-id=giantswarm-io-external-dns
        - --txt-prefix={{ .Values.clusterID }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.metricsPort }}
            scheme: HTTP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.metricsPort }}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
      {{- if eq .Values.provider "azure" }}
        volumeMounts:
        - name: azure-config-file
          mountPath: /azure/config
          readOnly: true
        - mountPath: /azure
          name: azure-config-file-ownership
      volumes:
      - name: azure-config-file
        hostPath:
          path: /etc/kubernetes/config
      - emptyDir: {}
        name: azure-config-file-ownership
      {{- end }}
