apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-dns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
    giantswarm.io/monitoring_basic_sli: "true"
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "external-dns.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "external-dns.labels" . | nindent 8 }}
        {{- if and (eq .Values.provider "gcp") (.Values.gcpProject) }}
        giantswarm.io/gcp-workload-identity: enabled
        {{- end }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "giantswarm.podAnnotations" . }}
      {{- if or .Values.secretConfiguration.enabled .Values.podAnnotations }}
      annotations:
        {{- if .Values.secretConfiguration.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "external-dns.serviceAccountName" . }}
      {{- with .Values.shareProcessNamespace }}
      shareProcessNamespace: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      initContainers:
        {{- include "giantswarm.deploymentInitContainers" . | nindent 8 }}
      containers:
        {{- if and (or (eq .Values.provider "aws") (eq .Values.provider "capa")) (eq .Values.aws.access "internal") ( eq .Values.aws.irsa "false") }}
        - name: "{{ .Release.Name }}-check-iam"
          image: {{ .Values.image.registry }}/giantswarm/alpine:3.16.2
          command:
          - /bin/sh
          - -c
          - while wget -qO- http://169.254.169.254/latest/meta-data/iam/security-credentials/ | grep -q {{ template "aws.iam.role" . }} ; do sleep 30 ; done && exit 1
          securityContext:
            readOnlyRootFilesystem: true
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        - name: external-dns
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "external-dns.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- include "giantswarm.deploymentEnv" . | nindent 12 }}
          args:
            - --log-level={{ .Values.logLevel }}
            - --log-format={{ .Values.logFormat }}
            - --interval={{ .Values.interval }}
            {{- if .Values.triggerLoopOnEvent }}
            - --events
            {{- end }}
            {{- range .Values.sources }}
            - --source={{ . }}
            {{- end }}
            - --policy={{ .Values.policy }}
            - --annotation-filter={{- template "annotation.filter" . }}
            {{- include "dnsProvider.flags" . | nindent 12 }}
            {{- if .Values.namespaceFilter }}
            - --namespace={{ .Values.namespaceFilter }}
            {{- end }}
            {{- if .Values.minEventSyncInterval }}
            - --min-event-sync-interval={{ .Values.minEventSyncInterval }}
            {{- end }}
            - --registry=txt
            - --txt-owner-id={{- template "txt.owner.id" . }}
            - --txt-prefix={{- template "txt.prefix" . }}
            {{- range .Values.domainFilters }}
            - --domain-filter={{ . }}
            {{- end }}
          {{- range .Values.extraArgs }}
            - {{ tpl . $ }}
          {{- end }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 7979
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- if or .Values.secretConfiguration.enabled .Values.extraVolumeMounts (eq .Values.provider "azure") }}
          volumeMounts:
            {{- if eq .Values.provider "azure" }}
            - name: config
              mountPath: /config
              readOnly: true
            {{- end }}
            {{- if .Values.secretConfiguration.enabled }}
            - name: secrets
              mountPath: {{ tpl .Values.secretConfiguration.mountPath $ }}
            {{- with .Values.secretConfiguration.subPath }}
              subPath: {{ tpl . $ }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if or .Values.secretConfiguration.enabled .Values.extraVolumes (eq .Values.provider "azure") }}
      volumes:
        {{- if eq .Values.provider "azure" }}
        - name: config
          emptyDir: {}
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes
        {{- end }}
        {{- if .Values.secretConfiguration.enabled }}
        - name: secrets
          secret:
            secretName: {{ include "external-dns.fullname" . }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
