apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring_basic_sli: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
      annotations:
        {{- if and (eq .Values.provider "aws") (eq .Values.aws.access "internal") }}
        {{- if .Values.aws.iam.customRole }}
        iam.amazonaws.com/role: {{ .Values.aws.iam.customRoleName }}
        {{- else }}
        iam.amazonaws.com/role: {{ .Values.clusterID}}-Route53Manager-Role
        {{- end }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.metricsPort }}"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
        fsGroup: {{ .Values.groupID }}
      priorityClassName: giantswarm-critical
      {{- if and (eq .Values.provider "aws") (eq .Values.aws.access "internal") }}
      initContainers:
      - name: wait-for-iam-role
        image: {{ .Values.image.registry }}/giantswarm/alpine:3.12.0
        command:
        - /bin/sh
        - -c
        - counter=5; while ! wget -qO- http://169.254.169.254/latest/meta-data/iam/security-credentials/ | grep {{ .Values.clusterID}}-Route53Manager-Role; do echo 'Waiting for iam-role to be available...'; sleep 5; let "counter-=1"  ; if [ "$counter" -eq "0" ]; then exit 1; fi; done
      {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
        {{- if eq .Values.aws.access "external" }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-route53-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-route53-credentials
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.aws.region }}
        {{- end }}
        args:
        {{- range .Values.sources }}
        - --source={{ . }}
        {{- end }}
        - --provider={{ .Values.provider }}
        {{- if eq .Values.provider "azure" }}
        - --azure-config-file=/azure/config/azure.yaml
        {{- end }}
        {{- if eq .Values.aws.access "external" }}
        - --domain-filter={{ .Values.aws.baseDomain }}
        - --aws-zone-type=public
        - --aws-prefer-cname
        {{- else }}
        - --domain-filter={{ .Values.baseDomain }}
        {{- end }}
        - --metrics-address=:{{ .Values.metricsPort }}
        - --namespace={{ .Values.global.endpointNamespace }}
        - --registry=txt
        - --txt-owner-id=giantswarm-io-external-dns
        {{- if .Values.registry.txtPrefix }}
        - --txt-prefix={{ .Values.registry.txtPrefix }}
        {{- else }}
        - --txt-prefix={{ .Values.clusterID }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.metricsPort }}
            scheme: HTTP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.metricsPort }}
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - name: metrics
          containerPort: {{ .Values.metricsPort }}
          protocol: TCP
      {{- if eq .Values.provider "azure" }}
        volumeMounts:
        - name: azure-config-file
          mountPath: /azure/config
          readOnly: true
        - mountPath: /azure
          name: azure-config-file-ownership
      volumes:
      - name: azure-config-file
        hostPath:
          path: /etc/kubernetes/config
      - emptyDir: {}
        name: azure-config-file-ownership
      {{- end }}
