apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: {{ .Values.global.metrics.port }}
    targetPort: metrics
  selector:
    {{- include "external-dns.selectorLabels" . | nindent 4 }}
