kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "external-dns.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  egress:
  - {}

