kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: {{ .Values.global.metrics.port }}
      protocol: TCP
  egress:
  - {}

