{{- if .Values.e2e }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: giantswarm-critical
  labels:
    {{- include "labels.common" . | nindent 4 }}
value: 1000000000
globalDefault: false
description: "This priority class is used by giantswarm kubernetes components."
{{- end }}
