apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  privileged: false
  runAsUser:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.global.securityContext.userID }}
        max: {{ .Values.global.securityContext.userID }}
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.global.securityContext.groupID }}
        max: {{ .Values.global.securityContext.groupID }}
  volumes:
  - 'secret'
  - 'configMap'
  - 'hostPath'
  - 'emptyDir'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.global.securityContext.fsGroupID }}
        max: {{ .Values.global.securityContext.fsGroupID }}
  readOnlyRootFilesystem: false
