{{- if le (int .Capabilities.KubeVersion.Minor) 24 }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
spec:
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.global.securityContext.fsGroupID }}
        max: {{ .Values.global.securityContext.fsGroupID }}
  hostIPC: false
  {{- if .Values.hostNetwork }}
  hostNetwork: true
  hostPorts:
  - min: {{ .Values.service.port }}
    max: {{ .Values.service.port }}
  {{- end }}
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: false
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.global.securityContext.groupID }}
        max: {{ .Values.global.securityContext.groupID }}
  runAsUser:
    rule: 'MustRunAs'
    ranges:
      - min: {{ .Values.global.securityContext.userID }}
        max: {{ .Values.global.securityContext.userID }}
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'configMap'
  - 'secret'
  {{- if eq .Values.provider "azure" }}
  - 'emptyDir'
  - 'hostPath'
  {{- end }}
  {{- if has .Values.provider (list "gcp" "capa") }}
  - 'projected'
  {{- end }}
{{- end }}
