apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: external-dns
    helmChart:
      name: external-dns
      version: v1.20.0
      repository:
        url: https://kubernetes-sigs.github.io/external-dns/
- path: helm/external-dns-app
  contents:
  - path: .
    directory:
      path: vendor/external-dns
    excludePaths:
      - CHANGELOG.md
      - RELEASE.md
    ignorePaths:
      - Chart.yaml
      - Chart.lock
      - README.md
      - README.md.gotmpl
      - .kube-linter.yaml
