# Default values for external-dns-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: external-dns

global:

  # global.endpointNamespace
  # The namespace to limit sources of endpoints to.
  endpointNamespace: kube-system

serviceType: "managed"

securityContext:
  userID: 65534
  groupID: 65534
  fsGroupID: 65534

aws:

  # aws.access
  # Route53 access type. Use 'internal' for all hosted zones, or 'external' for
  # public zones only.
  access: internal

  # aws.baseDomain
  # If aws.access is 'external' then the domain to update must be set.
  baseDomain:

  # aws.region
  # If aws.access is 'external' then the AWS region must be set.
  region:

  # aws.iam
  iam:

    # aws.iam.customRole
    # If set, allows a user-created role to be assumed. Role must have access to a
    # policy which allows configuration of Route53 hosted zone(s).
    # e.g. customRoleName: route53-manager-role
    customRoleName:

# registry
registry:

  # registry.txtPrefix
  # String prefix applied to TXT registry records. See
  # https://github.com/kubernetes-sigs/external-dns/blob/master/docs/proposal/registry.md
  txtPrefix:

sources:
  - service
  # Disable ingress source by default.
  # - ingress

metricsPort: 7979

image:
  registry: quay.io
  name: giantswarm/external-dns
  # When updating tag make sure to also keep appVersion in Chart.yaml in sync
  tag: v0.7.6

resources:
  limits:
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi

# do not change any values below

e2e: false

baseDomain: gigantic.io

# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: en2jo

# provider is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
provider: azure
