# Default values for external-dns-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: external-dns
namespace: kube-system

userID: 65534
groupID: 65534

baseDomain: gigantic.io
# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: en2jo
# provider is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
provider: azure
# route53/access describes route53 access type.
# possible values: internal/external.
# for external - secret+key/region should be specified.
route53:
  access: internal
  secret:
    name:
    namespace:
    key:
  region:

sources:
  - service
  # Disable ingress source by default.
  # - ingress

metricsPort: 10254

image:
  registry: quay.io
  name: giantswarm/external-dns
  tag: v0.5.11

resources:
  limits:
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi
