# Default values for external-dns-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: external-dns
namespace: kube-system

serviceType: "managed"

e2e: false

userID: 65534
groupID: 65534

baseDomain: gigantic.io
# clusterID is dynamic environment value, calculated after cluster creation
# applies only to Giant Swarm clusters
clusterID: en2jo
# provider is dynamic environment value, which comes from application catalog configuration
# applies only to Giant Swarm clusters
provider: azure
# aws/access describes route53 access type.
# possible values: internal/external.
aws:
  access: internal
  baseDomain:
  region:

sources:
  - service
  # Disable ingress source by default.
  # - ingress

metricsPort: 7979

image:
  registry: quay.io
  name: giantswarm/external-dns
  # When updating tag make sure to also keep appVersion in Chart.yaml in sync
  tag: v0.7.4

resources:
  limits:
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi
