{{- if .Values.crd.install }}
  {{- if .Capabilities.APIVersions.Has "cilium.io/v2" }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "kyverno-stack.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-7"
    {{- include "annotations.crd" . | nindent 4 }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
      app.kubernetes.io/component: crd-install
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "6443"
  {{- else}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-crd-install
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "annotations.crd" . | nindent 4 }}
    helm.sh/hook-weight: "-7"
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
spec:
  podSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
      app.kubernetes.io/component: crd-install
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
    ports:
    - port: 443
      protocol: TCP
    - port: 6443
      protocol: TCP
  ingress: []
  {{- end }}
{{- end }}
