{{- if .Values.crd.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-crd
  annotations:
    {{- include "annotations.crd" . | nindent 4 }}
    helm.sh/hook-weight: "-2"
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: crd
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Release.Name }}-crd
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-crd
  annotations:
    {{- include "annotations.crd" . | nindent 4 }}
    helm.sh/hook-weight: "-2"
  labels:
    {{- include "labels.common" . | nindent 4 }}
    app.kubernetes.io/component: crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-crd
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-crd
  namespace: {{ .Release.Namespace }}
{{- end }}
