#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ; readonly dir
cd "${dir}/.."

# Stage 1 sync
set -x
vendir sync
{ set +x; } 2>/dev/null

# Remove trailing whitespace end of lines (hack to fix vendir bug)
find vendor/ -type f -exec sed -i 's/[[:space:]]*$//' {} \;

# Patches
./sync/patches/network-policies/patch.sh
./sync/patches/deployment/patch.sh
./sync/patches/crds/patch.sh
./sync/patches/vpa/patch.sh
./sync/patches/helper/patch.sh
./sync/patches/values/patch.sh

HELM_BASE="helm/external-dns-app"
VENDIR_BASE="vendor/external-dns"

# Store diffs
rm -f ./diffs/*
for f in $(git --no-pager diff --no-exit-code --no-color --no-index "$VENDIR_BASE" "$HELM_BASE" --name-only) ; do
        # Skip /dev/null.
        [[ "$f" == "/dev/null" ]] && continue
        # Skip $HELM_BASE/Chart.yaml; as we take it as our own.
        [[ "$f" == "$HELM_BASE/Chart.yaml" ]] && continue
        [[ "$f" == "$HELM_BASE/Chart.lock" ]] && continue
        # Skip $HELM_BASE/README.md; as it's autogenerated.
        [[ "$f" == "$HELM_BASE/README.md" ]] && continue
        # Skip CRDs
        [[ "$f" =~ ^$HELM_BASE/crds/.* ]] && continue
        [[ "$f" =~ ^$HELM_BASE/files/.* ]] && continue

        base_file="$VENDIR_BASE/${f#"$HELM_BASE/"}"
        [[ ! -e $base_file ]] && base_file="/dev/null"

        set +e
        set -x

        git --no-pager diff --no-exit-code --no-color --no-index "$base_file" "${f}" \
                > "./diffs/${f//\//__}.patch" # ${f//\//__} replaces all "/" with "__"

        { set +x; } 2>/dev/null
        set -e

        ret=$?
        if [ $ret -ne 0 ] && [ $ret -ne 1 ] ; then
                exit $ret
        fi
done
