
# backoffLimit
# setting this higher means the CRD creation is less likely to be marked
# as failed.
backoffLimit: 10

# image
image:
  pullPolicy: IfNotPresent

# install
# CRDs are installed by default. If this is disabled then CRDs must
# be managed by another method.
install: true

# resources
resources:
  # resources.requests
  # Minimum resources requested for the job.
  requests:
    cpu: 100m
    memory: 256Mi

  # resources.limits
  # Maximum resources available for the job.
  limits:
    cpu: 500m
    memory: 512Mi
