{{ if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Release.Name }}-crd-install
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-7"
    {{- include "annotations.crd" . | nindent 4 }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
spec:
  endpointSelector:
    matchLabels:
      {{- include "external-dns.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: crd-install
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "6443"
{{- end }}
