apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-crd-install
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "crd.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-5"
  labels:
    {{- include "crd.labels" . | nindent 4 }}
data:
  dnsendpoints.yaml: |
{{ tpl ( .Files.Get "files/dnsendpoints.yaml" ) . | indent 4 }}
