{{- if le (int .Capabilities.KubeVersion.Minor) 24 }}
{{- if .Values.crd.install }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.Name }}-crd-install
  annotations:
    {{- include "annotations.crd" . | nindent 4 }}
    helm.sh/hook-weight: "-6"
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  volumes:
  - configMap
  - secret
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
{{- end }}
{{- end }}
