apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-crd-install
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "crd.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-4"
  labels:
    {{- include "crd.labels" . | nindent 4 }}
