apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-crd-install
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "annotations.crd" . | nindent 4 }}
    helm.sh/hook-weight: "-4"
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
    app.kubernetes.io/component: crd-install
